name: Deploy to GitHub Pages on push

on:
  push:
    branches: [ main ]
  # Uncomment and configure below to trigger on pull requests too
  # pull_request:
  #   branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Build Docusaurus website
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          # Change the email and username if you want to customize 
          # commit author information
          user_name: github-actions[bot]
          user_email: 4189828+github-actions[bot]@users.noreply.github.com

